name: Keep Alive Service secound update

on:
  schedule:
    - cron: '0 */1 * * *'  # هر ساعت در دقیقه 0
  workflow_dispatch:  # امکان اجرای دستی

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Send Keep Alive Request
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -d '{}' \
          "https://hiuhsxwympjeugkiusbd.supabase.co/rest/v1/keepalive"
